import { Metadata } from 'next'
import { Register } from '@/views'

export const metadata: Metadata = {
  title: 'Register Insta',
  description: 'Generated by create next app',
}

const RegisterPage = () => {
  return (
    <>
      <Register />
    </>
  )
}

export default RegisterPage
