import { Metadata } from 'next'
import { Home } from '@/views'

export const metadata: Metadata = {
  title: 'Home Insta',
  description: 'Generated by create next app',
}

const HomePage = () => {
  return (
    <main className="flex w-full h-full">
      <Home />
    </main>
  )
}

export default HomePage
