import { Metadata } from 'next'
import { Posts } from '@/views'
import { Layout } from '@/components'

export const metadata: Metadata = {
  title: 'Home Insta',
  description: 'Generated by create next app',
}

const HomePage = () => {
  return (
    <Layout>
      <main className="flex w-full h-full overflow-y-auto items-start justify-start">
        <Posts />
      </main>
    </Layout>
  )
}

export default HomePage
