import { Metadata } from 'next'
import { Posts } from '@/views'

export const metadata: Metadata = {
  title: 'Posts Insta',
  description: 'Generated by create next app',
}

const PostPage = () => {
  return (
    <main className="flex w-full h-full overflow-y-auto items-start justify-start">
      <Posts />
    </main>
  )
}

export default PostPage
