import { Metadata } from 'next'
import { Posts } from '@/views'

export const metadata: Metadata = {
  title: 'Posts Insta',
  description: 'Generated by create next app',
}

const RegisterPage = () => {
  return (
    <main className="flex w-full h-full items-center justify-center">
      <Posts />
    </main>
  )
}

export default RegisterPage
