import { Metadata } from 'next'
import { Login } from '@/views'

export const metadata: Metadata = {
  title: 'Login Insta',
  description: 'Generated by create next app',
}

const LoginPage = () => {
  return (
    <>
      <Login />
    </>
  )
}

export default LoginPage
