import { Metadata } from 'next'
import { Profile } from '@/views'

export const metadata: Metadata = {
  title: 'My Insta',
  description: 'Generated by create next app',
}

const UserPage = () => {
  return (
    <main className="flex w-full h-full items-center justify-center">
      <Profile />
    </main>
  )
}

export default UserPage
